/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author scarletspeedster
 */
class EmptyStringException extends Exception
{
    String msg;
    EmptyStringException(String msg)
    {
        this.msg=msg;
    }
    public String getMessage()
    {
        return msg;
    }
}
class MarksRangeException extends Exception
{
    String msg;
    MarksRangeException(String msg)
    {
        this.msg=msg;
    }
    
    public String getMessage()
    {
        return msg;
    }
}

public class ReportCard extends java.awt.Frame {

    /**
     * Creates new form ReportCard
     */
    public ReportCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        tf1 = new java.awt.TextField();
        tf2 = new java.awt.TextField();
        tf3 = new java.awt.TextField();
        tf4 = new java.awt.TextField();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label3 = new java.awt.Label();
        label8 = new java.awt.Label();
        label10 = new java.awt.Label();
        label9 = new java.awt.Label();
        label11 = new java.awt.Label();
        ct1 = new java.awt.TextField();
        ct2 = new java.awt.TextField();
        ct3 = new java.awt.TextField();
        jt1 = new java.awt.TextField();
        jt2 = new java.awt.TextField();
        jt3 = new java.awt.TextField();
        pt1 = new java.awt.TextField();
        pt2 = new java.awt.TextField();
        pt3 = new java.awt.TextField();
        lt1 = new java.awt.TextField();
        lt2 = new java.awt.TextField();
        lt3 = new java.awt.TextField();
        ht1 = new java.awt.TextField();
        ht2 = new java.awt.TextField();
        ht3 = new java.awt.TextField();
        label12 = new java.awt.Label();
        total = new java.awt.TextField();
        label13 = new java.awt.Label();
        per = new java.awt.TextField();
        gradeLabel = new java.awt.Label();
        button1 = new java.awt.Button();

        setBackground(new java.awt.Color(255, 255, 255));
        setName("MyFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(255, 255, 255));
        label1.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 0, 102));
        label1.setName(""); // NOI18N
        label1.setText("Student's Report Card");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 240, 30));

        label2.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(0, 0, 255));
        label2.setText("Father's Name");
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        label6.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        label6.setForeground(new java.awt.Color(0, 0, 255));
        label6.setText("Student Name");
        add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        label7.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        label7.setForeground(new java.awt.Color(0, 0, 255));
        label7.setText("Roll Number");
        add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 140, 20));
        add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 140, 20));
        add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 140, 20));
        add(tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 140, 20));

        label4.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        label4.setForeground(new java.awt.Color(0, 0, 255));
        label4.setText("Mother's Name");
        add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        label5.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        label5.setForeground(new java.awt.Color(102, 0, 0));
        label5.setText("Subject      Internal(25)     External(75)      Total");
        add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 450, -1));

        label3.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(0, 51, 204));
        label3.setText("C++");
        add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        label8.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        label8.setForeground(new java.awt.Color(0, 51, 204));
        label8.setText("Java");
        add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        label10.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        label10.setForeground(new java.awt.Color(0, 51, 204));
        label10.setText("PHP");
        add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        label9.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        label9.setForeground(new java.awt.Color(0, 51, 204));
        label9.setText("Linux");
        add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        label11.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        label11.setForeground(new java.awt.Color(0, 51, 204));
        label11.setText("HTML");
        add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));
        add(ct1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 70, -1));
        add(ct2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 70, -1));

        ct3.setEditable(false);
        add(ct3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 70, -1));
        add(jt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 70, -1));
        add(jt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 70, -1));

        jt3.setEditable(false);
        add(jt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 70, -1));
        add(pt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 70, -1));
        add(pt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 70, -1));

        pt3.setEditable(false);
        add(pt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 70, -1));
        add(lt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 70, -1));
        add(lt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 70, -1));

        lt3.setEditable(false);
        lt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lt3ActionPerformed(evt);
            }
        });
        add(lt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 70, -1));
        add(ht1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 70, -1));

        ht2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ht2ActionPerformed(evt);
            }
        });
        add(ht2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 70, -1));

        ht3.setEditable(false);
        add(ht3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 70, -1));

        label12.setFont(new java.awt.Font("Chandas", 1, 18)); // NOI18N
        label12.setForeground(new java.awt.Color(102, 0, 0));
        label12.setText("Percentage");
        add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, -1, -1));

        total.setEditable(false);
        add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 110, 30));

        label13.setFont(new java.awt.Font("Chandas", 1, 18)); // NOI18N
        label13.setForeground(new java.awt.Color(102, 0, 0));
        label13.setText("Total Marks");
        add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, -1));

        per.setEditable(false);
        add(per, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 110, 30));

        gradeLabel.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        gradeLabel.setForeground(new java.awt.Color(0, 51, 204));
        add(gradeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 420, 30));

        button1.setFont(new java.awt.Font("Ubuntu Mono", 1, 12)); // NOI18N
        button1.setLabel("Calculate Result");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 640, 110, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void lt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lt3ActionPerformed

    private void ht2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ht2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ht2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        try
        {
        String name,fname,mname,rollnumber;
        float mi1,mi2,mi3,mi4,mi5,me1,me2,me3,me4,me5,t1,t2,t3,t4,t5,ttl,percentage;
        char grade;
        name=tf1.getText();
        if(name.isEmpty())
        {
            throw new EmptyStringException("Please Enter The Student Name ");
        }
        rollnumber=tf2.getText();
        if(rollnumber.isEmpty())
        {
            throw new EmptyStringException("Please Enter The Roll Number ");
        }
        fname=tf3.getText();
        if(fname.isEmpty())
        {
            throw new EmptyStringException("Please Enter The Father's Name ");
        }
        mname=tf4.getText();
        if(mname.isEmpty())
        {
            throw new EmptyStringException("Please Enter The Mother's Name ");
        }
        
        mi1=Float.parseFloat(ct1.getText());
        if(mi1<0||mi1>25.0)
        {
            throw new MarksRangeException("Please Enter Correct Internal Marks of C++");
        }       
        me1=Float.parseFloat(ct2.getText());
        if(me1<0||me1>75)
        {
            throw new MarksRangeException("Please Enter Correct External Marks of C++");
        }
        mi2=Float.parseFloat(jt1.getText());
        if(mi2<0||mi2>25)
        {
            throw new MarksRangeException("Please Enter Correct Internal Marks of Java");
        }
        me2=Float.parseFloat(jt2.getText());
        if(me2<0||me2>75)
        {
            throw new MarksRangeException("Please Enter Correct External Marks of Java");
        }
        mi3=Float.parseFloat(pt1.getText());
        if(mi3<0||mi3>25)
        {
            throw new MarksRangeException("Please Enter Correct Internal Marks of PHP");
        }
        me3=Float.parseFloat(pt2.getText());
        if(me3<0||me3>75)
        {
            throw new MarksRangeException("Please Enter Correct External Marks of PHP");
        }
        mi4=Float.parseFloat(lt1.getText());
        if(mi4<0||mi4>25)
        {
            throw new MarksRangeException("Please Enter Correct Internal Marks of Linux");
        }
        me4=Float.parseFloat(lt2.getText());
        if(me4<0||me4>75)
        {
            throw new MarksRangeException("Please Enter Correct External Marks of Linux");
        }
        mi5=Float.parseFloat(ht1.getText());
        if(mi5<0||mi5>25)
        {
            throw new MarksRangeException("Please Enter Correct Internal Marks of HTML");
        }
        me5=Float.parseFloat(ht2.getText());
        if(me5<0||me5>75)
        {
            throw new MarksRangeException("Please Enter Correct External Marks of HTML");
        }
        t1=mi1+me1;t2=mi2+me2;t3=mi3+me3;t4=mi4+me4;t5=mi5+me5;
        ttl=t1+t2+t3+t4+t5;
        percentage=ttl/5;
        
            if(percentage>=70)
            {
                grade='A';
            }
            else if(percentage>=60)
            {
                grade='B';
            }
                else
            {
                grade='C';
            }
        ct3.setText(String.valueOf(t1));
        jt3.setText(String.valueOf(t2));
        pt3.setText(String.valueOf(t3));
        lt3.setText(String.valueOf(t4));
        ht3.setText(String.valueOf(t5));
        total.setText(String.valueOf(ttl));
        per.setText(String.valueOf(percentage +" %"));
        gradeLabel.setText(name+" , You got "+grade+" grade");
        }
        catch(EmptyStringException e)
        {
            gradeLabel.setText(e.getMessage());
        }
        catch(MarksRangeException e)
        {
            gradeLabel.setText(e.getMessage());
        }
        
        catch(Exception e)
        {
            gradeLabel.setText("Please enter the Marks in Numeric");
        }
        
        
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportCard().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.TextField ct1;
    private java.awt.TextField ct2;
    private java.awt.TextField ct3;
    private java.awt.Label gradeLabel;
    private java.awt.TextField ht1;
    private java.awt.TextField ht2;
    private java.awt.TextField ht3;
    private java.awt.TextField jt1;
    private java.awt.TextField jt2;
    private java.awt.TextField jt3;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.TextField lt1;
    private java.awt.TextField lt2;
    private java.awt.TextField lt3;
    private java.awt.TextField per;
    private java.awt.TextField pt1;
    private java.awt.TextField pt2;
    private java.awt.TextField pt3;
    private java.awt.TextField tf1;
    private java.awt.TextField tf2;
    private java.awt.TextField tf3;
    private java.awt.TextField tf4;
    private java.awt.TextField total;
    // End of variables declaration//GEN-END:variables
}
